version: '3'
services:
  mysql:
    image: "mysql:latest"
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: "root"
volumes:
  test-redis-data:
